# Generated by Django 4.2.5 on 2023-09-09 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
