# Generated by Django 4.2.5 on 2023-09-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_customprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customprofile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="customprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
