# Generated by Django 4.2.4 on 2023-08-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={
                "verbose_name": "Actors (they are literally me)",
                "verbose_name_plural": "Actors (they are literally me)",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Categories (literally me)",
                "verbose_name_plural": "Categories (literally me)",
            },
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "Movies (literally me)",
                "verbose_name_plural": "Movies (literally me)",
            },
        ),
        migrations.AlterField(
            model_name="movie",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movies",
                to="mainapp.category",
            ),
        ),
    ]
