# Generated by Django 4.2.4 on 2023-08-09 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_actor_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "Actors (they are literally me)",
                "verbose_name_plural": "Actors (they are literally me)",
            },
        ),
    ]
