# Generated by Django 4.2.4 on 2023-08-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_alter_actor_options_alter_movie_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
