# Generated by Django 4.2.4 on 2023-08-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0010_alter_commentanswer_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="photo",
            field=models.ImageField(upload_to="actor_photos"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(upload_to="movie_posters"),
        ),
    ]
