# Generated by Django 4.2.4 on 2023-08-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0011_alter_actor_photo_alter_movie_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer",
            field=models.FileField(blank=True, upload_to="movie_trailers"),
        ),
    ]
