# Generated by Django 4.2.4 on 2023-08-30 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0013_alter_movie_create_time_alter_movie_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
